apiVersion: v1
kind: Pod
metadata:
  name: attack-pod
  namespace: secscan
  labels:
    app: attack      
spec:
  containers:
  - name: attack-container
    image: ubuntu
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
    - path: /etc
      type: Directory
