apiVersion: v1
kind: Pod
metadata:
  annotations:
    labels:
    name: attack-pod
    namespace: default
spec:
  containers:
  - image: ubuntu
    imagePullPolicy: IfNotPresent
    name: attack-container
