apiVersion: v1
kind: Pod
metadata:
  name: attack-pod
  namespace: secscan
  labels:
    app: attack      
spec:
  volumes:
  - name: test-volume
    hostPath:
      path: /
      type: Directory
  containers:
  - name: attack-container
    image: ubuntu
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test-volume
      mountPath: /root
      readOnly: true
