apiVersion: v1
kind: Pod
metadata:
  name: attack-pod
  namespace: secscan
  labels:
    app: attack      
spec:
  containers:
  - name: attack-container
    image: ubuntu
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /root
      name: mount-root-info-mnt
    volumes:
    - name: mount-root-info-mnt
      hostDir:
        path: /
